# Generated by Django 5.1.1 on 2024-10-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeletas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraccion',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='infraccion',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='infraccion',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='papeleta',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='papeleta',
            name='pagada',
        ),
        migrations.AlterField(
            model_name='conductor',
            name='licencia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='papeleta',
            name='fecha',
            field=models.DateField(),
        ),
    ]
