# Generated by Django 5.1.1 on 2024-10-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeletas', '0002_remove_infraccion_codigo_remove_infraccion_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='conductores/'),
        ),
    ]
